from log import Log

log = Log("helloworld")
log.error("Unbekannter Fehler aufgetreten!")
